### ISSUE TITLE
1

### ISSUE THREAD

**Issue by MounaHoussein** [dpcs-dj/Issues#10] opened 2019-08-06 08:40 UTC
d

**Comment by MounaHoussein** [comment] 2019-08-06 08:40
[Siva->] Reported the issue to the product team, once we have the resolution we will update the same. Thanks.
--

**Comment by sivasreenivas** [comment] 2019-08-14 12:33
The issue is partially fixed, product team is working on full fix and will update when its available in the the UAT environment.

**Comment by sivasreenivas** [comment] 2019-08-19 14:01
Received the fix from the product team and will be moving the fixes to UAT on 21.08.2019 weekly build release. Attached the screenshots for reference from development environment.

![image](https://user-images.githubusercontent.com/53824291/63271412-c3fae100-c2a2-11e9-87ba-aaa08c1b3163.png)

![image](https://user-images.githubusercontent.com/53824291/63271441-d543ed80-c2a2-11e9-8531-92e8c456d8dc.png)

**Comment by sivasreenivas** [comment] 2019-08-21 07:15
@Abdirahim0 fix has been moved to UAT in the build v3.9.74 Please review and close the ticket.

![image](https://user-images.githubusercontent.com/53824291/63410584-52cf4100-c3fc-11e9-8884-2dd470109880.png)

![image](https://user-images.githubusercontent.com/53824291/63410600-58c52200-c3fc-11e9-8031-e3c025a42149.png)

**Comment by Abdirahim0** [comment] 2019-08-21 08:59
@sivasreenivas  This ticket is closed because Design issue was fixed. However other issues related to uat via mobile appeared as some modules that do not respond. @MohamedCheikh  Please check & create another ticket for that.

**Closed as completed by Abdirahim0** 2019-08-21 08:59 UTC
Labels: bug
